volumes:
  db_data:
  gem_cache:
  node_modules:

services:
  db:
    image: postgres:14.13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    image: evenly-backend-local
    container_name: evenly-backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/app:cached
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      DATABASE: evenly_development
      RAILS_ENV: development
    depends_on:
      - db
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    image: evenly-frontend-local
    container_name: evenly-frontend
    volumes:
      - ./frontend:/var/app:cached
      - node_modules:/var/app/node_modules
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    command: npm run dev